config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'shipping_addresses', to: 'users/registrations#new_shipping_address'
    post 'shipping_addresses', to: 'users/registrations#complete_user'
  end

  root to: "homes#index"

  resources :homes  do
    collection do
      get 'new', defaults: {format: 'json'}
    end
  end


  resources :categories, only: [:index] do
    member do
      get 'parent'
      get 'child'
      get 'grandchild'
    end
  end

  resources :items  do
    collection do
      get 'buyitem'
      get 'get_category_children', defaults: {format: 'json'}
      get 'get_category_grandchildren', defaults: {format: 'json'}
    end
    # 編集用
    member do
      get 'get_category_children', defaults: {format: 'json'}
      get 'get_category_grandchildren', defaults: {format: 'json'}
    end
  end


  resources :users, only: [:index, :show] do
    member do
      get 'logout', 'edit_profile', 'edit_shipping_address', 'update_complete'
      patch 'update_profile', 'update_shipping_address'
    end
    resources :cards, except: [:show, :edit, :update]
  end

  resources :transaction, only: [] do
    member do
      get   'buy',     to: 'transaction#buy'
      post  'pay',     to: 'transaction#pay'
      get   'sold',    to: 'transaction#sold'
      get   'done',    to: 'transaction#done'
      get   'error',   to: 'transaction#error'
      get   'card',    to: 'transaction#card'
      post  'card',    to: 'transaction#register_card'
      get   'address', to: 'transaction#address'
      patch 'address', to: 'transaction#update_address'
    end
    
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, :name_first, :name_last, :name_first_kana, :name_last_kana, :birth, presence: true
  validates :nickname, uniqueness: true
  validates :password, presence: true, on: :create
  validates :password, format: { with: /\A[a-z0-9]+\z/i }, on: :update, allow_blank: true
  validates :name_first, :name_last, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "全角で入力してください" }
  validates :name_first_kana, :name_last_kana, format: { with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/, message: "全角カタカナで入力してください" }
  has_one :shipping_address, dependent: :destroy

  mount_uploader :profile_image, MypageImageUploader
  has_many :histories
  has_one :card, dependent: :destroy
  has_many :items
  
  scope :pickup_parents, -> { where(ancestry: nil)}
  
  # has_many :items, through: :historiesとしてしまうと自分の出品商品一覧が取得できなくなるため、
  # 別途自分が購入した商品を取得するメソッドの定義を行う。
  def bought_item
    item_ids = []
    self.histories.each do |history|
      item_ids << history.item_id
    end
    Item.includes(:item_images).find(item_ids)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :set_parents, only: :edit

  # GET /resource/sign_up
  # def new
  #   super
  # end
  def new
    @user = User.new
  end

  # POST /resource
  # def create
  #   super
  # end
  def create
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @shipping_address = @user.build_shipping_address
    render :new_shipping_address
  end

  def complete_user
    @user = User.new(session["devise.regist_data"]["user"])
    @shipping_address = ShippingAddress.new(shipping_address_params)
    unless @shipping_address.valid?
      flash.now[:alert] = @shipping_address.errors.full_messages
      render :new_shipping_address and return
    end
    @user.build_shipping_address(@shipping_address.attributes)
    if @user.save
      sign_in(:user, @user)
    else
      render :new
    end
  end

  def after_update_path_for(resource)
    update_complete_user_path(current_user.id)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  def shipping_address_params
    params.require(:shipping_address).permit(:name_first, :name_last, :name_first_kana, :name_last_kana, :zipcode, :prefecture_id, :city, :street_address, :building, :phone_number)
  end

  def set_parents
    @parents = Category.pickup_parents
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, except: :index
  before_action :set_parents, only:[:show, :logout, :edit_profile, :edit_shipping_address, :update_complete]

  # 新規登録画面用
  def index
  end

  # マイページメイン画面用
  def show
    @bought_items = current_user.bought_item
    @sales = 0
    current_user.items.each do |item|
      @sales += (item.price * 0.9).round if item.history.present?
    end
  end

  # マイページからのログアウト用
  def logout
  end

  # プロフィール編集用
  def edit_profile
  end

  # プロフィール更新用
  def update_profile
    if @user.update(user_params)
      redirect_to update_complete_user_path, notice: '更新しました'
    else
      flash.now[:error] = '更新失敗'
      render update_complete_user_path
    end
  end

  # 送付先住所編集用
  def edit_shipping_address
  end

  # 送付先住所更新用
  def update_shipping_address
    if @shipping_address.update(shipping_address_params)
      redirect_to update_complete_user_path, notice: '更新しました'
    else
      flash.now[:error] = '更新失敗'
      render :edit_shipping_address
    end
  end

  def update_complete
  end

  private
  def user_params
    params.require(:user).permit(:nickname, :profile_image, :profile)
  end

  def shipping_address_params
    params.require(:shipping_address).permit(:name_first, :name_last, :name_first_kana, :name_last_kana, :zipcode, :prefecture_id, :city, :street_address, :building, :phone_number)
  end

  def set_user
    @user = User.find(params[:id])
    @shipping_address = ShippingAddress.find(params[:id])
  end

  def set_parents
    @parents = Category.pickup_parents
  end
  

end

app/views/users/_mypage_main.html.haml
.mypage__main
  .mypage__main__top
    .mypage__main__top__title
      #{current_user.nickname}さんのマイページ
    .mypage__main__top__profileBox
      .mypage__main__top__profileBox__profile
        - if @user.profile_image.present?
          .mypage__main__top__profileBox__profile--img
            = image_tag @user.profile_image.url, size: "100x100"
        - else
          .mypage__main__top__profileBox__profile--dummy
            イメージ画像
      .mypage__main__top__profileBox__info
        .mypage__main__top__profileBox__info__top
          .mypage__main__top__profileBox__info__top__items
            出品数：#{current_user.items.count}
        .mypage__main__top__profileBox__info__profit
          = "今までの利益：¥#{@sales}"
  .mypage__main__container
    %ul.mypage__main__container__menu
      %li.mypage__main__container__menu__title#favorite.active
        お気に入り
      %li.mypage__main__container__menu__title#buy
        購入商品
      %li.mypage__main__container__menu__title#sale
        出品商品
    %ul.mypage__main__container__itemBox
      %li.mypage__main__container__itemBox__list.show
      %li.mypage__main__container__itemBox__list
        - @bought_items.each do |item|
          .mypage__main__container__itemBox__list__item
            = link_to item_path(item.id), method: :get do
              .item-image
                = image_tag item.item_images.first.image_URL.url, width: '178px', class: 'img'
              .item-name
                = item.items_name
              .item-price
                = number_with_delimiter(item.price)
                円（税込み）
      %li.mypage__main__container__itemBox__list
        - current_user.items.each do |item|
          .mypage__main__container__itemBox__list__item
            = link_to item_path(item.id), method: :get do
              .item-image
                = image_tag item.item_images.first.image_URL.url, width: '178px', class: 'img'
              .item-name
                = item.items_name
              .item-price
                = number_with_delimiter(item.price)
                円（税込み）
                - if item.history.present?
                  %br 【売却済み】

app/views/users/_mypage_sidebar.html.haml
.mypage__sidebar
  .mypage__sidebar__box
    %ul.mypage__sidebar__box__list
      .mypage__sidebar__box__list__item#mypage
        = link_to "/users/#{current_user.id}" do
          マイページ
          = icon('fa', 'chevron-right')
      %li.mypage__sidebar__box__list__item#rate
        = link_to "#" do
          評価
          = icon('fa', 'chevron-right')
  .mypage__sidebar__box
    %h4.mypage__sidebar__box__title 商品
    %ul.mypage__sidebar__box__list
      %li.mypage__sidebar__box__list__item#sale
        = link_to new_item_path do
          出品する
          = icon('fa', 'chevron-right')
      %li.mypage__sidebar__box__list__item#saleItem
        = link_to items_path do
          出品した商品
          = icon('fa', 'chevron-right')
      %li.mypage__sidebar__box__list__item#buyItem
        = link_to buyitem_items_path do
          購入した商品
          = icon('fa', 'chevron-right')
      %li.mypage__sidebar__box__list__item#favoriteItem
        = link_to "#" do
          お気に入り
          = icon('fa', 'chevron-right')
  .mypage__sidebar__box
    %h4.mypage__sidebar__box__title 設定
    %ul.mypage__sidebar__box__list
      %li.mypage__sidebar__box__list__item#profile
        = link_to edit_profile_user_path(current_user.id) do
          プロフィール
          = icon('fa', 'chevron-right')
      %li.mypage__sidebar__box__list__item#shipping
        = link_to edit_shipping_address_user_path(current_user.id) do
          送付先変更
          = icon('fa', 'chevron-right')
      %li.mypage__sidebar__box__list__item#MailPassword
        = link_to edit_user_registration_path(current_user.id) do
          メール・パスワード変更
          = icon('fa', 'chevron-right')
      %li.mypage__sidebar__box__list__item#creditcard
        = link_to user_cards_path(current_user.id) do
          お支払い方法設定
          = icon('fa', 'chevron-right')
      %li.mypage__sidebar__box__list__item#logout
        = link_to logout_user_path(current_user.id) do
          ログアウト
          = icon('fa', 'chevron-right')

app/views/users/edit_profile.html.haml
= render 'homes/headerMain'
.mainbox
  .mypage
    = render "users/mypage_sidebar"

    .mypage__main
      .mypage__main__top
        .editProfile
          = form_for(@user, url: update_profile_user_path) do |f|
            .editProfile__title
              プロフィール
            .editProfile__main
              .editProfile__main__imgbox
                プロフィール画像
                .editProfile__main__imgbox--img
                  =f.label :profile_image do
                    - if @user.profile_image.present?
                      = image_tag @user.profile_image.url, class: 'profile_image', size: "100x100"
                    - else
                      = image_tag ('material/icon/mypage_sample.png'), class: 'profile_image', size: "100x100"
                    = f.file_field :profile_image, class: 'hidden'
              .editProfile__main__nickname
                = f.text_field :nickname

            .editProfile__message
              .editProfile__message__title
                = f.label :profile, "プロフィール"
              .editProfile__message__sentence
                = f.text_area :profile, size: "70x10", placeholder: '例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪'

            .editProfile__update
              .editProfile__update--button
                = f.submit "更新"

= render 'homes/footerMain'

app/views/users/edit_shipping_address.html.haml
-# マイページ 送付先住所編集画面
= render 'homes/headerMain'

.mainbox
  .mypage
    = render "users/mypage_sidebar"
    .mypage__main
      .mypage__main__top
        .userCreate__userinfo__title
          送付先住所変更
        .userCreate__userinfo__body
          = form_for(@shipping_address, url: update_shipping_address_user_path) do |f|
            = render partial: 'shared/address_form', locals: {f: f}

= render 'homes/footerMain'

app/views/users/index.html.haml
= render "shared/single_header"

.userCreate
  .userCreate__index
    .userCreate__index__title
      新規登録画面
    %ul.userCreate__index__pattern
      %li.userCreate__index__pattern__mail
        = link_to new_user_registration_path, method: :get do
          .userCreate__index__pattern__mail--login
            = icon('far', 'envelope', class: "userCreate__index__pattern__mail--icon")
            %span<>
            メールアドレスで登録

-# 画面下部に余白がでないようにする
.footerMargin
= render "shared/single_footer"

app/views/users/logout.html.haml
= render 'homes/headerMain'
.mainbox
  .mypage
    = render "users/mypage_sidebar"
    .mypageLogout
      .mypageLogout__title
        = link_to destroy_user_session_path, method: :delete do
          .mypageLogout__title--button
            ログアウト
= render 'homes/footerMain'
= render 'homes/sellBtn'

app/views/users/show.html.haml
= render 'homes/headerMain'
.mainbox
  .mypage
    = render "users/mypage_sidebar"
    = render "users/mypage_main"
= render 'homes/footerMain'
= render 'homes/sellBtn'

app/views/users/update_complete.html.haml
-# ユーザ情報更新後の完了画面
= render 'homes/headerMain'
.mainbox
  .mypage
    = render "users/mypage_sidebar"
    .mypage__main
      .updateBox
        - flash.each do |key, value|
          = content_tag :div, value, class: key
        .updateBox__title
          = link_to "/users/#{current_user.id}" do
            .updateBox__title--button
              マイページトップへ
= render 'homes/footerMain'
= render 'homes/sellBtn'