config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'shipping_addresses', to: 'users/registrations#new_shipping_address'
    post 'shipping_addresses', to: 'users/registrations#complete_user'
  end

  root to: "homes#index"

  resources :homes  do
    collection do
      get 'new', defaults: {format: 'json'}
    end
  end


  resources :categories, only: [:index] do
    member do
      get 'parent'
      get 'child'
      get 'grandchild'
    end
  end

  resources :items  do
    collection do
      get 'buyitem'
      get 'get_category_children', defaults: {format: 'json'}
      get 'get_category_grandchildren', defaults: {format: 'json'}
    end
    # 編集用
    member do
      get 'get_category_children', defaults: {format: 'json'}
      get 'get_category_grandchildren', defaults: {format: 'json'}
    end
  end


  resources :users, only: [:index, :show] do
    member do
      get 'logout', 'edit_profile', 'edit_shipping_address', 'update_complete'
      patch 'update_profile', 'update_shipping_address'
    end
    resources :cards, except: [:show, :edit, :update]
  end

  resources :transaction, only: [] do
    member do
      get   'buy',     to: 'transaction#buy'
      post  'pay',     to: 'transaction#pay'
      get   'sold',    to: 'transaction#sold'
      get   'done',    to: 'transaction#done'
      get   'error',   to: 'transaction#error'
      get   'card',    to: 'transaction#card'
      post  'card',    to: 'transaction#register_card'
      get   'address', to: 'transaction#address'
      patch 'address', to: 'transaction#update_address'
    end
    
  end
end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController
  require 'payjp'
  before_action :move_to_login
  before_action :set_item
  before_action :move_to_sold, only: [:buy, :pay]
  before_action :set_user_address, only: [:buy, :done, :address, :update_address]
  before_action :set_payjp_key, only: [:buy, :pay, :done, :card,:register_card]
  before_action :set_card_info, only: [:buy, :done, :card, :update_address]

  # 購入確認画面
  def buy
  end

  # 支払い処理
  def pay
    card = current_user.card
    # カードが削除されていないかチェックする (手順:購入確認画面を開いた状態で、別タブからカード情報を削除したあと、購入を確定する)
    redirect_to action: :error, id: @item.id and return unless card.card_id

    # 先にhistoryテーブルへ保存。PayjpAPIがエラーを返してきたらロールバックする。
    History.transaction do 
      History.create(user_id: current_user.id, item_id: @item.id)
      @result = Payjp::Charge.create(
        amount:   @item.price,
        customer: card.customer_id,
        currency: "jpy"
      )
      redirect_to action: :done, id: @item.id 
      return
    end
    rescue Payjp::CardError
    redirect_to action: :error, id: @item.id
    return
  end

  # 売り切れ時の処理
  def sold
  end

  # 購入完了画面
  def done
  end

  # payjpアクセスでのエラー時
  def error
  end

  def card
  end

  def register_card
    token = params["payjp-token"]

    if token.blank? # トークンの取得に失敗していたらやりなおしを求める
      @error_message = "カードの登録に失敗しました。もう一度お試しください。"
      render :card, id: @item.id
    else
      if current_user.card.blank?
        # ユーザーがcardテーブルを持っていない場合の処理
        customer = Payjp::Customer.create(
          description: "test", 
          card: token, 
          metadata: {user_id: current_user.id}
          )

        card = Card.new(
          user_id: current_user.id, 
          customer_id: customer.id, 
          card_id: customer.default_card
          )
        
        if card.save
          redirect_to action: :buy, id: @item.id
        else
          @error_message = "カードの登録に失敗しました。もう一度お試しください。"
          render :card, id: @item.id
        end

      else
        # ユーザーがcardテーブルを持っている場合の処理
        card = current_user.card
        customer = Payjp::Customer.retrieve(card.customer_id)
        response = customer.cards.create(card: token, default: true)

        if card.update(card_id: response.id)
          redirect_to action: :buy, id: @item.id
        else
          @error_message = "カードの登録に失敗しました。もう一度お試しください。"
          render :card, id: @item.id
        end
      end
    end
  end

  def address
  end

  def update_address
    if @address.update(shipping_address_params)
      render action: :buy, user_id: @item.id
    else
      flash.now[:error] = '更新失敗'
      render action: :address, user_id: @item.id
    end
  end
  
  private
  def move_to_login
    redirect_to new_user_session_path unless user_signed_in?
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def move_to_sold # インスタンス変数@itemを用いているためset_itemより後に呼び出す必要があります。
    redirect_to action: :sold, id: @item.id if @item.history
  end

  def set_user_address
    @address = current_user.shipping_address
  end

  def set_payjp_key # payjpの秘密鍵をセットする
    Payjp.api_key = Rails.application.credentials[:payjp][:secret_key]
  end

  def set_card_info # カード情報登録済みなら、カード情報を取得してビューに渡します。
    card = current_user.card 
    if card.present? && card.card_id.present?
      customer = Payjp::Customer.retrieve(card.customer_id)
      @card_info = customer.cards.retrieve(card.card_id)
    end
  end

  def shipping_address_params
    params.require(:shipping_address).permit(:name_first, :name_last, :name_first_kana, :name_last_kana, :zipcode, :prefecture_id, :city, :street_address, :building, :phone_number)
  end
end

app/views/transaction/address.html.haml
= render "shared/single_header"
.single-main
  .single-container
    .userCreate__userinfo__title
      送付先住所変更
    .userCreate__userinfo__body
      = form_with model: @address, url: address_transaction_path(@item.id), method: :patch, local: true do |f|
        = render partial: 'shared/address_form', locals: {f: f}
= render "shared/single_footer"

app/views/transaction/buy.html.haml
= render "shared/single_header"

.single-main
  .single-container
    .single-container__header
      購入内容の確認

    .single-container__box
      .single-container__box--inner
        .buy-item
          .buy-item__image
            = image_tag @item.item_images.first.image_URL.url, height: 80
          .buy-item__detail
            .buy-item__detail--name
              = @item.items_name
            .buy-item__detail--price
              = "¥#{number_with_delimiter(@item.price)} (税込) #{@item.shipping_costs.split("(")[0]}"

    .single-container__box
      .single-container__box--inner
        .buy-price
          .buy-price--left
            支払い金額
          .buy-price--right
            = "¥#{number_with_delimiter(@item.price)}"

        .pay-method
          .pay-method__header
            支払い方法
          .pay-method__main
            - if @card_info.present?
              クレジットカード
              %br/
              = "**** **** **** #{@card_info.last4}"
              %br/
              有効期限
              = format("%02d / %02d", @card_info.exp_month, @card_info.exp_year.to_s.slice(2,3))
              %br/
              = render "cards/card_logo"
            - else
              .pay-method__main--register
                = link_to card_transaction_path(@item.id) do
                  = icon('fas', 'plus-circle')
                  登録してください
          
        .user-address
          .user-address__header
            .user-address__header--title
              配送先
            .user-address__header--fix
              = link_to "変更する", address_transaction_path(@item.id)
          .user-address__main
            .user-address__main--address
              = "〒#{@address.zipcode[0, 3]}-#{@address.zipcode[3, 4]}"
              = "#{@address.prefecture.name} #{@address.city} #{@address.street_address} #{@address.building}"
            .user-address__main--name
              = "#{@address.name_last} #{@address.name_first}"

        .submit-buy
          - if @card_info.present? && @item.history.blank? && current_user.id != @item.user_id
            = link_to pay_transaction_path(@item.id), method: :post do
              .submit-buy__button
                購入する
          - else 
            .submit-buy--disabled
              購入する

= render "shared/single_footer"

app/views/transaction/card.html.haml
= render "shared/single_header"
.single-main
  .single-container
    .card-form__header
      .card-form__headerTitle
        支払い方法
    .card-form__main
      .card-form__mainForm
        = form_with method: :post, id: "charge-form", name: "inputForm", local: true do |f|
          = render partial: "cards/card_form", locals: {f: f, error_message: @error_message}
= render "shared/single_footer"

app/views/transaction/done.html.haml
= render "shared/single_header"

.single-main
  .single-container
    .single-container__header
      購入が完了しました

    .single-container__box
      .single-container__box--inner
        .buy-item
          .buy-item__image
            = image_tag @item.item_images.first.image_URL.url, height: 80
          .buy-item__detail
            .buy-item__detail--name
              = @item.items_name
            .buy-item__detail--price
              = "¥#{number_with_delimiter(@item.price)} (税込) #{@item.shipping_costs.split("(")[0]}"

    .single-container__box
      .single-container__box--inner
        .buy-price
          .buy-price--left
            支払い金額
          .buy-price--right
            = "¥#{number_with_delimiter(@item.price)}"

        .user-address
          .user-address__header
            .user-address__header--title
              配送先
          .user-address__main
            .user-address__main--address
              = "〒#{@address.zipcode[0, 3]}-#{@address.zipcode[3, 4]}"
              = "#{@address.prefecture.name} #{@address.city} #{@address.street_address} #{@address.building}"
            .user-address__main--name
              = "#{@address.name_last} #{@address.name_first}"

        .pay-method
          .pay-method__header
            支払い方法
          .pay-method__main
            = "**** **** **** #{@card_info.last4}"
            %br/
            有効期限
            = format("%02d / %02d", @card_info.exp_month, @card_info.exp_year.to_s.slice(2,3))
            %br/
            = render "cards/card_logo"

        .back-home
          = link_to "トップに戻る", root_path

= render "shared/single_footer"

app/views/transaction/error.html.haml
= render "shared/single_header"

.single-main
  .single-container
    .single-container__header
      エラーが発生したため購入に失敗しました
    .single-container__box
      .single-container__box--inner
        .back-item-detail
          = link_to "商品画面に戻る", item_path(@item.id)

-# 画面下部に余白がでないようにする
.purchaseFooterMargin
= render "shared/single_footer"

app/views/transaction/sold.html.haml
= render "shared/single_header"

.single-main
  .single-container
    .single-container__header
      商品はすでに売り切れています
  
    .single-container__box
      .single-container__box--inner
        .back-item-detail
          = link_to "商品画面に戻る", item_path(@item.id)

-# 画面下部に余白がでないようにする
.purchaseFooterMargin
= render "shared/single_footer"