config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'shipping_addresses', to: 'users/registrations#new_shipping_address'
    post 'shipping_addresses', to: 'users/registrations#complete_user'
  end

  root to: "homes#index"

  resources :homes  do
    collection do
      get 'new', defaults: {format: 'json'}
    end
  end


  resources :categories, only: [:index] do
    member do
      get 'parent'
      get 'child'
      get 'grandchild'
    end
  end

  resources :items  do
    collection do
      get 'buyitem'
      get 'get_category_children', defaults: {format: 'json'}
      get 'get_category_grandchildren', defaults: {format: 'json'}
    end
    # 編集用
    member do
      get 'get_category_children', defaults: {format: 'json'}
      get 'get_category_grandchildren', defaults: {format: 'json'}
    end
  end


  resources :users, only: [:index, :show] do
    member do
      get 'logout', 'edit_profile', 'edit_shipping_address', 'update_complete'
      patch 'update_profile', 'update_shipping_address'
    end
    resources :cards, except: [:show, :edit, :update]
  end

  resources :transaction, only: [] do
    member do
      get   'buy',     to: 'transaction#buy'
      post  'pay',     to: 'transaction#pay'
      get   'sold',    to: 'transaction#sold'
      get   'done',    to: 'transaction#done'
      get   'error',   to: 'transaction#error'
      get   'card',    to: 'transaction#card'
      post  'card',    to: 'transaction#register_card'
      get   'address', to: 'transaction#address'
      patch 'address', to: 'transaction#update_address'
    end
    
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @item = Item.limit(3).includes(:history, :item_images).order('created_at DESC')
    @parents  = Category.where(ancestry: nil)
  end

  def new
    @children = Category.find(params[:parent_id]).children
    respond_to do |format|
      format.html
      format.json
    end
  end

end

app/views/homes/_footerMain.html.haml
%footer.footerMain
  %ul.footerContents
    %li.content
      %h2.content__head
        FURIMAについて
      %ul
        %li<
          = link_to '会社概要（運営会社）',"#"
        %li<
          = link_to 'プライバシーポリシー', "#"
        %li<
          = link_to 'FURIMA利用規約', "#" 
        %li<
          = link_to 'ポイントに関する特約', "#"

    %li.content
      %h2.content__head
        FURIMAを見る
      %ul
        %li<
          = link_to 'カテゴリー一覧', "#"
        %li<
          = link_to 'ブランド一覧', "#"

    %li.content
      %h2.content__head
        ヘルプ＆ガイド
      %ul
        %li<
          = link_to 'FURIMAガイド', "#"
        %li<
          = link_to 'FURIMAロゴ利用ガイドライン', "#"
        %li<
          = link_to 'お知らせ', "#"

  .footer__logo
    = image_tag 'material/logo/logo-white.png', height: '47', width: '160', class: 'img'
  %p © FURIMA

app/views/homes/_headerMain.html.haml
%header.headerMain
  .headerBox
    .headerBox__top
      .headerBox__top__logo
        = link_to root_path do
          = image_tag 'material/logo/logo.png', height: '40', width: '140', class: 'img'
      .headerBox__top__searchBox
        %input.headerBox__top__searchBox__form{:name => "search", :placeholder => "キーワードから探す"}/
        .headerBox__top__searchBox__icon
          = image_tag 'material/icon/icon-search 1.png', height: '20', width: '20'


    .headerBox__bottom
      .headerBox__bottom__left
        .headerBox__bottom__left__category
          %details
            %summary カテゴリ
            %ul.parents_list
              - @parents .each do |parent|
                %li= link_to "#{parent.name}", parent_category_path(parent.id), class: "parent_category",id: "#{parent.id}"
            %ul.children_list
            %ul.grand_children_list

        .headerBox__bottom__left__brand
          %details
            %summary ブランド
      %a.headerBox__bottom__right
        - if user_signed_in?
          .headerBox__bottom__right__login
            = link_to "マイページ", "/users/#{current_user.id}"
          .headerBox__bottom__right__signup
            = link_to "ログアウト", destroy_user_session_path, method: :delete
        - else
          .headerBox__bottom__right__login
            = link_to "ログイン", new_user_session_path, method: :get
          .headerBox__bottom__right__signup
            = link_to "新規登録", users_path

app/views/homes/_main.html.haml
%main.main
  .mainVisual
    .mainVisual-desc
      %h2.mainVisual-desc__headline 人生を変えるフリマアプリ
      .mainVisual-desc__text
        FURIMAはだれでもかんたんに出品・購入できる<br>フリマアプリです
      .mainVisual-desc__btn
        .mainVisual-desc__btn__appleBtn
          = link_to image_tag('material/icon/appStoreLogo.svg', height: '54', width: '180', ),"#",crass:"img"
        .mainVisual-desc__btn__googleBtn
          = link_to image_tag('material/icon/googlePlayLogo.svg', height: '54', width: '180', ),"#",crass:"img"
  
  .reason
    %h2.reason__head FURIMAが選ばれる3つの理由
    %ul.reason-desc
      %li.reason-desc__list
        .reason-desc__image
          %span.number 1
          = image_tag 'material/pict/pict-reason-01.jpg', height: '306', width: '306', class: 'img'
        %h3.reason-desc__headline
          %span.color 3分
          ですぐに出品
        .reason-desc__text スマホで入力するだけで簡単に出品できる！
      %li.reason-desc__list
        .reason-desc__image
          %span.number 2
          = image_tag 'material/pict/pict-reason-02.jpg', height: '306', width: '306', class: 'img'
        %h3.reason-desc__headline
          %span.color シンプル
          で使いやすい
        .reason-desc__text めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.reason-desc__list
        .reason-desc__image
          %span.number 3
          = image_tag 'material/pict/pict-reason-03.jpg', height: '306', width: '306', class: 'img'
        %h3.reason-desc__headline
          手数料
          %span.color 業界最安
          
        .reason-desc__text 最大3%でお得に出品&購入！

  .middleBanner
    .middleBanner-desc
      %h2.middleBanner-desc__headline 会員数日本一位
      .middleBanner-desc__text
        FURIMAは、フリマアプリで最も人気。<br>
        出品・購入回数も業界最多です！<br>
        ほしかったあの商品に出会えるかもしれません。<br>
      .middleBanner-desc__btn
        .middleBanner-desc__btn__appleBtn
        = link_to image_tag('material/icon/appStoreLogo.svg', height: '54', width: '180', ),"#",crass:"img"
        .middleBanner-desc__btn__googleBtn
        = link_to image_tag('material/icon/googlePlayLogo.svg', height: '54', width: '180', ),"#",crass:"img"

  .feature
    %h2.feature__head FURIMAの特徴
    %ul.feature-desc
      %li.feature-desc__list
        .feature-desc__image
          = image_tag 'material/icon/icon-01.png', width: '200', class: 'img'
        %h3.feature-desc__headline
          簡単に売り買いできる
        .feature-desc__text スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %li.feature-desc__list
        .feature-desc__image
          = image_tag 'material/icon/icon-03.png', width: '200', class: 'img'
        %h3.feature-desc__headline
          売上金は即日振込みに対応
        .feature-desc__text 午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      %li.feature-desc__list
        .feature-desc__image
          = image_tag 'material/icon/icon-04.png', width: '200', class: 'img'
        %h3.feature-desc__headline
          様々な支払いに対応
        .feature-desc__text お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

  .container
    %h2.container__head ピックアップカテゴリー
    .containerBox
      .containerBox__headline 新規投稿商品
      .containerBox__lists
        - @item.each do |item|
          .containerBox-list
            - if item.history
              .containerBox-list__sold
                .containerBox-list__sold__inner
                  SOLD
          = link_to item_path(item.id), method: :get do
            .containerBox-list__image
              = image_tag item.item_images.first.image_URL.url,width: '220px',  class: 'img'
            .containerBox-list__detail
              %h3.name
              =item.items_name
              %ul.desc
                %li.price
                  = number_with_delimiter(item.price)
                  円
                %li.like
                  %i.fa.fa-star 0
              %p.tax（税込み）



  .bottomBanner
    .bottomBanner-desc
      %h2.bottomBanner-desc__headline だれでもかんたん、人生を変えるフリマアプリ
      .bottomBanner-desc__text 今すぐ無料ダウンロード！
      .bottomBanner-desc__btn
        .bottomBanner-desc__btn__appleBtn
        = link_to image_tag('material/icon/appStoreLogo.svg', height: '54', width: '180', ),"#",crass:"img"
        .bottomBanner-desc__btn__googleBtn
        = link_to image_tag('material/icon/googlePlayLogo.svg', height: '54', width: '180', ),"#",crass:"img"

app/views/homes/_sellBtn.html.haml
- if user_signed_in?
  = link_to new_item_path do
    .sellBtn--login
      出品する
      .sellBtn--image
      = image_tag 'material/icon/icon_camera.png',height: '54', width: '54', class: 'btn'

- else
  = link_to new_user_session_path do
    .sellBtn--logout
      ログインして
      %br 出品
      .sellBtn--image
      = image_tag 'material/icon/icon_camera.png',height: '54', width: '54', class: 'btn'

app/views/homes/index.html.haml
.wrapper
  = render 'headerMain'
  = render 'main'
  = render 'footerMain'
  = render 'sellBtn'