config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'shipping_addresses', to: 'users/registrations#new_shipping_address'
    post 'shipping_addresses', to: 'users/registrations#complete_user'
  end

  root to: "homes#index"

  resources :homes  do
    collection do
      get 'new', defaults: {format: 'json'}
    end
  end


  resources :categories, only: [:index] do
    member do
      get 'parent'
      get 'child'
      get 'grandchild'
    end
  end

  resources :items  do
    collection do
      get 'buyitem'
      get 'get_category_children', defaults: {format: 'json'}
      get 'get_category_grandchildren', defaults: {format: 'json'}
    end
    # 編集用
    member do
      get 'get_category_children', defaults: {format: 'json'}
      get 'get_category_grandchildren', defaults: {format: 'json'}
    end
  end


  resources :users, only: [:index, :show] do
    member do
      get 'logout', 'edit_profile', 'edit_shipping_address', 'update_complete'
      patch 'update_profile', 'update_shipping_address'
    end
    resources :cards, except: [:show, :edit, :update]
  end

  resources :transaction, only: [] do
    member do
      get   'buy',     to: 'transaction#buy'
      post  'pay',     to: 'transaction#pay'
      get   'sold',    to: 'transaction#sold'
      get   'done',    to: 'transaction#done'
      get   'error',   to: 'transaction#error'
      get   'card',    to: 'transaction#card'
      post  'card',    to: 'transaction#register_card'
      get   'address', to: 'transaction#address'
      patch 'address', to: 'transaction#update_address'
    end
    
  end
end

app/models/item.rb
class Item < ApplicationRecord

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images, allow_destroy: true
  has_many   :comments
  belongs_to :category
  belongs_to :brand, optional: true
  belongs_to :user  
  has_one    :rating
  has_one    :history

  validates :items_name, :item_description, :condition, :shipping_costs, :days_to_ship, :price, :category_id, :prefecture_id, presence: true
  validates :items_name, length: {maximum: 40}
  validates :price, presence: true,numericality: {only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}

  scope :pickup_parents, -> { where(ancestry: nil)}
  scope :parentItems, -> (params){ where(category_id: params) }
  scope :childItems, -> (grandchild){ where(category_id: grandchild) }
  scope :grandchildItems, -> (params){ where(category_id: params) }

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_parents, only: [:index, :show, :edit, :buyitem]
  before_action :move_to_login, except: :show
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :item_purchased?, only: [:edit, :update, :destroy]

  # 出品した商品一覧表示用
  def index
    @items = current_user.items.order('created_at DESC')
  end

  def buyitem
    @bought_items = current_user.bought_item
  end

  def new
    @item = Item.new
    @item.item_images.new
    @category_parent_array = Category.where(ancestry: nil)
  end

  def create
    @item = Item.new(item_params)
    if @item.save!
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @category = @item.category
  end

  # 出品商品編集用
  def edit
    if @item.user_id != current_user.id
      redirect_to root_path
    end

    grandchild_category = @item.category
    child_category = grandchild_category.parent

    @category_parent_array = Category.where(ancestry: nil)
    @category_children_array =  Category.where(ancestry: child_category.ancestry)
    @category_grandchildren_array = Category.where(ancestry: grandchild_category.ancestry)

  end

  # 編集した商品更新用
  def update
    if params[:item].keys.include?("item_image") || params[:item].keys.include?("item_images_attributes") 
      if @item.valid?
        if params[:item].keys.include?("item_image") 
          update_images_ids = params[:item][:item_image].values
          before_images_ids = @item.item_images.ids
          before_images_ids.each do |before_img_id|
            ItemImage.find(before_img_id).destroy unless update_images_ids.include?("#{before_img_id}") 
          end
        else
          before_images_ids = @item.item_images.ids
          before_images_ids.each do |before_img_id|
            ItemImage.find(before_img_id).destroy 
          end
        end
        @item.update(item_params)
        redirect_to update_complete_user_path(current_user.id), notice: "商品を更新しました"
      else
        flash.now[:error] = '更新失敗'
        render 'users/update_complete' 
      end
    else
      redirect_back(fallback_location: root_path)
    end
  end

  # 商品削除用
  def destroy
    if @item.user.id == current_user.id
      if @item.destroy
        redirect_to update_complete_user_path(current_user.id), notice: "商品を削除しました"
      else
        redirect_to update_complete_user_path(current_user.id), alert: '削除に失敗しました'
      end
    else
      flash.now[:error] = '削除できません'
      render 'users/update_complete'
    end
  end

  def get_category_children
    @category_children = Category.find(params[:parent_id]).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  private
  def item_params
    params.require(:item).permit(:items_name,
        :item_description,
        :condition,
        :shipping_costs,
        :days_to_ship,
        :price,
        :category_id,
        :brand_id,
        :prefecture_id,
        item_images_attributes: [:image_URL, :_destroy, :id]).merge(user_id: current_user.id)
  end
  
  def set_parents
  @parents = Category.pickup_parents
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def move_to_login
    redirect_to new_user_session_path unless user_signed_in?
  end

  def item_purchased?
    if @item.history.present?
      flash.now[:error] = '購入済みの商品の編集/削除はできません'
      render 'users/update_complete' 
    end
  end
end

app/views/items/_form.html.haml
.body
  = form_for @item do |f|
    .form
      .form__items__main
        .form__items__main__title
          商品画像
          %span 必須
        .form__items__main__text 
          最大5枚までアップロードできます
        .flexbox
          .new-wrapper__main__preview
          %label{id: "image-wrapper"}
            .form__items__main__image--field
              %i{class: "fas fa-camera"}
              .form__items__main__image--field__text
                クリックして選択
            =f.fields_for :item_images do |image|
              =image.file_field :image_URL ,class: "js-file"
      .form__items
        .form__items__name
          .form__items__name--title
            =f.label :name , "商品名"
            %span
              必須
          .form__items__name--column
            = f.text_field :items_name, placeholder: "40文字まで",class: "validate required"
        .form__items__description
          .form__items__description--title
            =f.label :item_description, "商品の説明"
            %span 
              必須
          .form__items__description--column
            = f.text_area :item_description, placeholder: "商品の説明", class: "validate sentence"
      .form__details
        .form__details__category
          .form__details__category--title
            %p.description-name
              商品詳細
            = f.label :category_id, "カテゴリー",class: "list__category"
            %span
              必須
          .form__details__category--column
            = f.collection_select :category_id , @category_parent_array, :id , :name, {include_blank: "---"}, {id:'list__category__parent'}
        .form__details__brand
          .form__details__brand--title
            =f.label :brand_id, "ブランド名" 
            %span
              任意
          .form__details__brand--column
            = f.text_field :brand_id, placeholder: "例）シャネル"
        .form__details__condition
          .form__details__condition--title
            =f.label :condition , "商品の状態"
            %span
              必須
          .form__details__condition--column
            = f.select :condition, [["選択してください",""],["新品・未使用","新品・未使用"],["未使用に近い","未使用に近い"],["目立った傷や汚れ無し","目立った傷や汚れ無し"],["やや傷や汚れあり","やや傷や汚れあり"],["傷や汚れあり","傷や汚れあり"],["全体的に状態が悪い","全体的に状態が悪い"]],{},{class: "validate condition"}
      .form__ship
        .form__ship__cost
          .form__ship__cost--title
            %p
              配送について
            =f.label :shipping_costs, "配送料の負担" 
            %span
              必須
          .form__ship__cost--column
            = f.select :shipping_costs, [["選択してください",""],["送料込み(出品者負担)","送料込み(出品者負担)"],["着払い(購入者負担)","着払い(購入者負担)"]],{},{class: "validate cost"}
        .form__ship__area
          .form__ship__area--title
            =f.label :prefecture_id, "発送元の地域"
            %span
              必須
          .form__ship__area--column
            = f.collection_select :prefecture_id, Prefecture.all, :id, :name,{include_blank: "---"},{class:"validate prefecture"}
        .form__ship__days 
          .form__ship__days--title
            =f.label :days_to_ship, "発送までの日数"
            %span
              必須
          .form__ship__days--column
            = f.select :days_to_ship, [["選択してください",""],["1~2日で発送","1~2日で発送"],["3~4日で発送","3~4日で発送"],["5~6日で発送","5~6日で発送"]],{},{class: "validate days"}
      .form__sell
        .form__sell__price 
          .form__sell__price--title 
            %p
              価格 (¥300~9,999,999)
            = f.label :price, "販売価格"
            %span
              必須
          .form__sell__price--column 
            %p.suggest
              *半角数字入力
            %span
              ¥
            = f.number_field :price, placeholder: "0", id: "price__calc"
        .form__sell__calc
          .form__sell__calc--box
            %p
              販売手数料(10%)
          .form__sell__calc--result
            %p.result__fee
        .form__sell__profit
          .form__sell__profit--box
            %p
              販売利益
          .form__sell__profit--result
            %p.result__profit
        =f.submit '出品する', class: 'submit-btn'
        =f.button '戻る',type: "button" ,class: 'exit-btn', onClick: "history.back()"

app/views/items/buyitem.html.haml
= render 'homes/headerMain'
.mainbox
  .mypage
    = render "users/mypage_sidebar"

    .mypage__main
      .mypage__main__top
        .ex-items
          .ex-items__title
            購入商品
          .ex-items__box
            .ex-items__box__index.show
              - @bought_items.each do |item|
                .ex-items__box__index__item
                  .ex-items__box__index__item__img
                    = image_tag item.item_images.first.image_URL.url, width: '62px', height: '62px'
                  .ex-items__box__index__item__name
                    = item.items_name
                  .ex-items__box__index__item__btn
                    .ex-items__box__index__item__btn__show
                      = link_to "詳細", item_path(item.id), method: :get

= render 'homes/footerMain'

app/views/items/edit.html.haml
= render 'homes/headerMain'
.mainbox
  .mypage
    = render "users/mypage_sidebar"

    -# 出品商品編集画面
    .edit-body
      = form_for @item do |f|
        .form
          .form__items__main
            .form__items__main__title
              商品画像
              %span 必須
            .form__items__main__text 
              最大5枚までアップロードできます

            %ul#previews
              = f.fields_for :item_image do |item_image|
                - @item.item_images.each_with_index do |image, i|
                  %li.image-preview
                    %label.upload-label{style:"display: none;"}
                      .upload-label__text
                        = icon('fa', 'camera')
                        %br
                        クリックして選択
                        .input-area
                          = item_image.file_field :image_URL, value: image.image_URL ,class: "hidden image_upload"
                          = item_image.hidden_field :id, value: image.id, name: "item[item_image][#{i}]"
                    .image-preview__wapper
                      = image_tag image.image_URL.to_s, class:"preview"
                    .image-preview_btn
                      .image-preview_btn_delete
                        = icon('far', 'times-circle')

          .form__items
            .form__items__name
              .form__items__name--title
                =f.label :name , "商品名"
                %span
                  必須
              .form__items__name--column
                = f.text_field :items_name, placeholder: "40文字まで",class: "validate required"
            .form__items__description
              .form__items__description--title
                =f.label :item_description, "商品の説明"
                %span 
                  必須
              .form__items__description--column
                = f.text_area :item_description, placeholder: "商品の説明", class: "validate sentence"
          .form__details
            .form__details__category
              .form__details__category--title
                %p.description-name
                  商品詳細
                = f.label :category_id, "カテゴリー",class: "list__category"
                %span
                  必須
              .form__details__category--column
                = f.collection_select :category_id, @category_parent_array, :id, :name, { selected: @item.category.root.id }, { id: 'list__category__parent' }
              .form__details__category--children
                = f.collection_select :category_id, @category_children_array, :id, :name, { selected: @item.category.parent.id }, { id: 'list__category__children' }
              .form__details__category--grandchildren
                = f.collection_select :category_id, @category_grandchildren_array, :id, :name, { selected: @item.category.id }, { id: 'list__category__grandchildren' }

            .form__details__brand
              .form__details__brand--title
                =f.label :brand_id, "ブランド名" 
                %span
                  任意
              .form__details__brand--column
                = f.text_field :brand_id, placeholder: "例）シャネル"
            .form__details__condition
              .form__details__condition--title
                =f.label :condition , "商品の状態"
                %span
                  必須
              .form__details__condition--column
                = f.select :condition, [["選択してください",""],["新品・未使用","新品・未使用"],["未使用に近い","未使用に近い"],["目立った傷や汚れ無し","目立った傷や汚れ無し"],["やや傷や汚れあり","やや傷や汚れあり"],["傷や汚れあり","傷や汚れあり"],["全体的に状態が悪い","全体的に状態が悪い"]],{},{class: "validate condition"}
          .form__ship
            .form__ship__cost
              .form__ship__cost--title
                %p
                  配送について
                =f.label :shipping_costs, "配送料の負担" 
                %span
                  必須
              .form__ship__cost--column
                = f.select :shipping_costs, [["選択してください",""],["送料込み(出品者負担)","送料込み(出品者負担)"],["着払い(購入者負担)","着払い(購入者負担)"]],{},{class: "validate cost"}
            .form__ship__area
              .form__ship__area--title
                =f.label :prefecture_id, "発送元の地域"
                %span
                  必須
              .form__ship__area--column
                = f.collection_select :prefecture_id, Prefecture.all, :id, :name,{include_blank: "---"},{class:"validate prefecture"}
            .form__ship__days 
              .form__ship__days--title
                =f.label :days_to_ship, "発送までの日数"
                %span
                  必須
              .form__ship__days--column
                = f.select :days_to_ship, [["選択してください",""],["1~2日で発送","1~2日で発送"],["3~4日で発送","3~4日で発送"],["5~6日で発送","5~6日で発送"]],{},{class: "validate days"}
          .form__sell
            .form__sell__price 
              .form__sell__price--title 
                %p
                  価格 (¥300~9,999,999)
                = f.label :price, "販売価格"
                %span
                  必須
              .form__sell__price--column 
                %p.suggest
                  *半角数字入力
                %span
                  ¥
                = f.number_field :price, placeholder: "0", id: "price__calc"
            .form__sell__calc
              .form__sell__calc--box
                %p
                  販売手数料(10%)
              .form__sell__calc--result
                %p.result__fee
            .form__sell__profit
              .form__sell__profit--box
                %p
                  販売利益
              .form__sell__profit--result
                %p.result__profit
            =f.submit '更新する', class: 'submit-btn'

= render 'homes/footerMain'

app/views/items/index.html.haml
= render 'homes/headerMain'
.mainbox
  .mypage
    = render "users/mypage_sidebar"

    .mypage__main
      .mypage__main__top
        .ex-items
          .ex-items__title
            出品商品
          .ex-items__box
            .ex-items__box__index.show
              - @items.each do |item|
                .ex-items__box__index__item
                  .ex-items__box__index__item__img
                    = image_tag item.item_images.first.image_URL.url, width: '62px', height: '62px'
                  .ex-items__box__index__item__name
                    = item.items_name
                  .ex-items__box__index__item__sold
                    - if item.history
                      【売却済み】
                  .ex-items__box__index__item__btn
                  - if item.history
                    .ex-items__box__index__item__btn__delete
                      = link_to "削除", item_path(item), method: :delete, data: { confirm: "削除しますか？" }
                  - else
                    .ex-items__box__index__item__btn__edit
                      = link_to "編集", edit_item_path(item)
                    .ex-items__box__index__item__btn__delete
                      = link_to "削除", item_path(item), method: :delete, data: { confirm: "削除しますか？" }

= render 'homes/footerMain'

app/views/items/new.html.haml
= render "shared/single_header"
.main
  = render "form"

=render "shared/single_footer"

app/views/items/show.html.haml
= render "homes/headerMain"

.main
  .main__content
    .main__content__middle
      %h3.main__content__middle--name 
        = @item.items_name
      .image__box
        %ul.bigbox
          %li 
            - @item.item_images.each.with_index do |item_image,i|
              - if i==0
                = image_tag "#{item_image.image_URL}",height: '330px', width: '600px',class: 'bigPict'
            %ul.smallbox
              %li
                - @item.item_images.each.with_index do |item_image,i|
                  = image_tag "#{item_image.image_URL}", height: '90', width: '140'
      %p.explanation
        画像にカーソルを合わせると拡大されます
      .price__box
        %p.price
          ¥
          %span
            = @item.price
        %p.text
          (税込)送料込み
      .description__box
        = @item.item_description
      .table__box
        %table
          %tr
            %th 出品者
            %td 
              - if user_signed_in?
                = link_to user_path(@item.user) do
                  = @item.user.nickname
              - else
                = @item.user.nickname

          %tr
            %th カテゴリ
            %td
              = link_to parent_category_path(@category.root.id),class:"categoryLink" do
                = @category.root.name
                %br
              = link_to child_category_path(@category.parent.id),class:"categoryLink" do
                = @category.parent.name
                %br
              = link_to grandchild_category_path(@category.id),class:"categoryLink" do
                = @category.name
          %tr
            %th ブランド
            %td 
          %tr
            %th 商品の状態
            %td
              = @item.condition
          %tr
            %th 配送料の負担
            %td 
              = @item.shipping_costs
          %tr
            %th 発送元の地域
            %td 
              = @item.prefecture.name
          %tr
            %th 発送日の目安
            %td 
              = @item.days_to_ship
      - if @item.history.present?
        .main__content__middle--sold
          .sold-btn
            売り切れ
      - elsif user_signed_in? && current_user.id != @item.user_id
        .main__content__middle--buy
          = link_to "購入画面に進む", buy_transaction_path(@item.id),class:"button"
        .main__content__middle--option
          %ul
            %li.favorite
              =icon("fas","star")
              %span
                お気に入り
              %span
                0
            %li.calling
              =icon("fas","phone")
              %span
                不適切な商品の通報
      - elsif user_signed_in? && current_user.id == @item.user_id
        .main__content__middle--edit
          = link_to "編集する", edit_item_path(@item), class:"edit-btn"
        .main__content__middle--delete
          = link_to "削除する", item_path(@item), method: :delete, data: { confirm: "削除しますか？" }, class: "delete-btn"
      - else 
        .main__content__middle--login
          = link_to "ログインする","/users/sign_in",class:"login-btn"
        .main__content__middle--sign
          = link_to "新規登録する","/users/sign_up",class: "sign-btn"
    .main__content__comment
      %textarea
      .main__content__comment--message
        相手の事を考え丁寧なコメントを心掛けましょう
        %br
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      .main__content__comment--post
        = icon("fas","comment")
        %span
          = link_to "コメントする","#"
    .main__content__bottom
      %ul
        %li
          =icon("fas","arrow-left")
          %span
            前の商品
        %li
          後ろの商品
          %span
            =icon("fas","arrow-right")
      .main__content__category
        = link_to "メンズをもっと見る" ,"#",class:"category--tree"
.bottomBanner
  .bottomBanner-desc
    %h2.bottomBanner-desc__headline だれでもかんたん、人生を変えるフリマアプリ
    .bottomBanner-desc__text 今すぐ無料ダウンロード！
    .bottomBanner-desc__btn
      .bottomBanner-desc__btn__appleBtn
      = link_to image_tag('material/icon/appStoreLogo.svg', height: '54', width: '180', ),"#",crass:"img"
      .bottomBanner-desc__btn__googleBtn
      = link_to image_tag('material/icon/googlePlayLogo.svg', height: '54', width: '180', ),"#",crass:"img"

= render "homes/footerMain"